# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'FlashyTableviews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'APParallaxHeader'

  # Pods for FlashyTableviews

end
